name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  chart_it:
    path: ../
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  universal_platform: ^1.0.0+1
  responsive_sizer: ^3.1.1
  sidebarx: ^0.15.0
  salomon_bottom_bar: ^3.3.1
  flutter_displaymode:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true