import 'package:flutter/material.dart';

const lightTheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF6A4FA3),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFEADDFF),
  onPrimaryContainer: Color(0xFF25005A),
  secondary: Color(0xFF635B70),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE9DEF8),
  onSecondaryContainer: Color(0xFF1E182B),
  tertiary: Color(0xFF8A5100),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFFDCBD),
  onTertiaryContainer: Color(0xFF2C1600),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF1D1B1E),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF1D1B1E),
  surfaceVariant: Color(0xFFE7E0EB),
  onSurfaceVariant: Color(0xFF49454E),
  outline: Color(0xFF7A757F),
  onInverseSurface: Color(0xFFF5EFF4),
  inverseSurface: Color(0xFF323033),
  inversePrimary: Color(0xFFD2BBFF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF6A4FA3),
  outlineVariant: Color(0xFFCBC4CF),
  scrim: Color(0xFF000000),
);
