name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    name: Lint, Test And Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Lint
        run: flutter analyze --fatal-infos --fatal-warnings

#  TODO: Add test job
#  test:
